### PR TITLE
Update ad.svg

### PR DESCRIPTION
**Pull request by englishextra**
changed size to 240x160

### CODE REVIEW

**Comment by woble** [comment]
It is not necessary to change the `viewBox` value if you just want different `width` and `height`. I kept things as low as possible to have smallest files possible. This one in particular could in fact be changed to `0 0 12 6` with correct path values as well to make it even smaller.

**Comment by englishextra** [comment]
@woble Let me explain why it was important in my case.

I use batch file in SVGs folder to create PNGs for production:
```
mogrify -format png -type palettealpha *.svg
```
so I need png as img src. And there the image size was important.

If you meant SVGs as design source, then, yes, the size can be smaller, and you then scale it to your purposes.

**Comment by woble** [comment]
I will test what you provided later, but changing width and height should be more than enough I believe.

**Comment by englishextra** [comment]
@woble very well, thanks

BTW Changing only width and height didn't work in my case, I had to change d attr values taken from the nearest similar flag.

**Comment by woble** [comment]
Use the `-size` parameter to resize: `mogrify -format png -size 1000 -type palettealpha *.svg`. Tested and works as expected with latest ImageMagick w/ legacy utilities.

**Comment by englishextra** [comment]
@woble oh yeah, thanks, the issue is that I have lots of folders with svg as source. So initial size is important. Anyway, thanks for the tip.

**Comment by woble** [comment]
Tested with `ImageMagick 7.0.6-3 Q16 x64 2017-07-24` to see if changing only `width` and `height` works, and it does indeed work as expected.

**Pull request closed without merging**
